Repository technyon/nuki_hub, pull requests merged in 2024-06, with the labels that each got.

#373 Add HA keypad for opener
  src/NetworkOpener.cpp
  src/NetworkOpener.h
  src/NukiOpenerWrapper.cpp
Labels: enhancement

#385 Fix opener config
  README.md
  src/NukiOpenerWrapper.cpp
  src/NukiWrapper.cpp
Labels: bug

#384 Publish keypad code and rolling log, update BLEScanner to 1.1.0
  README.md
  lib/BleScanner/include/README
  lib/BleScanner/lib/README
  lib/BleScanner/library.json
  lib/BleScanner/platformio.ini
  lib/BleScanner/src/BleScanner.cpp
  lib/BleScanner/src/BleScanner.h
  src/MqttTopics.h
  src/Network.cpp
  src/NetworkLock.cpp
  src/NetworkLock.h
  src/NetworkOpener.cpp
  src/NetworkOpener.h
  src/NukiOpenerWrapper.cpp
  src/NukiWrapper.cpp
  src/PreferencesKeys.h
  src/WebCfgServer.cpp
Labels: enhancement

#386 Add GL-S10
  README.md
  src/Network.cpp
  src/Network.h
  src/WebCfgServer.cpp
Labels: enhancement

#379 webcfg: add header and meta refresh for main page
  src/WebCfgServer.cpp
  src/WebCfgServer.h
Labels: enhancement

#393 web: improve style for mobile view
  resources/README.md
  resources/style.css
  src/WebCfgServer.cpp
  src/WebCfgServerConstants.h
Labels: enhancement

#391 GitHub standards, bots and templates (Stale bot, Issue/PR templates, Code of conduct, Security policy, Contributing)
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/config.yml
  .github/issue-close-app.yml
  .github/workflows/stale-actions.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: enhancement

#389 Official MQTT - Nuki Hub coexistence, keypad/timecontrol sensor per code/entry, option not to publish config, authorization log improvements, various fixes
  Docker/Dockerfile_cmake
  HYBRID.md
  README.md
  src/MqttTopics.h
  src/Network.cpp
  src/Network.h
  src/NetworkLock.cpp
  src/NetworkLock.h
  src/NetworkOpener.cpp
  src/NetworkOpener.h
  src/NukiOpenerWrapper.cpp
  src/NukiOpenerWrapper.h
  src/NukiWrapper.cpp
  src/NukiWrapper.h
  src/PreferencesKeys.h
  src/WebCfgServer.cpp
  src/WebCfgServer.h
  src/main.cpp
  src/networkDevices/NetworkDevice.h
Labels: bug, documentation, enhancement

#394 web: main menu navigation rework
  resources/style.css
  src/WebCfgServer.cpp
  src/WebCfgServer.h
  src/WebCfgServerConstants.h
Labels: enhancement

#399 Fix operators
  src/NukiOpenerWrapper.cpp
  src/NukiWrapper.cpp
Labels: bug

#402 Change ESP32-S3 to 4MB build
  boards/nuki-esp32-s3.json
  platformio.ini
Labels: bug

#405 Fix release workflow
  .github/workflows/build.yml
Labels: bug

#411 Fix nr of retries
  src/NukiOpenerWrapper.cpp
  src/NukiWrapper.cpp
Labels: bug
