Repository technyon/nuki_hub, pull requests merged in 2025-01, with the labels that each got.

#587 OTA to alternate (Quad/Octal) PSRAM S3 binary
  src/Config.h
  src/WebCfgServer.cpp
Labels: enhancement

#589 Update NukiHub and Nuki device time using NTP
  src/Config.h
  src/NukiOpenerWrapper.cpp
  src/NukiOpenerWrapper.h
  src/NukiWrapper.cpp
  src/NukiWrapper.h
  src/PreferencesKeys.h
  src/WebCfgServer.cpp
  src/main.cpp
Labels: enhancement

#591 Memory optimizations, MQTT SPIFFS and SPIFFS Import/Export
  platformio.ini
  sdkconfig.defaults
  sdkconfig.singlecore.defaults
  src/Config.h
  src/PreferencesKeys.h
  src/WebCfgServer.cpp
  src/main.cpp
  src/networkDevices/NetworkDevice.cpp
  src/networkDevices/NetworkDevice.h
Labels: enhancement

#592 PSRAM Optimizations
  sdkconfig.defaults.esp32
  sdkconfig.defaults.esp32-s3
  sdkconfig.defaults.esp32-s3-oct
  sdkconfig.defaults.esp32-solo1
Labels: enhancement

#602 Fix endless reboot on webserver disable + Fix HA ID
  src/Config.h
  src/HomeAssistantDiscovery.cpp
  src/NukiNetwork.cpp
Labels: bug

#603 Pioarduino 3.1.1
  platformio.ini
  updater/platformio.ini
Labels: enhancement

#611 LilyGO T-ETH ELite (ESP32-S3+Ethernet POE) support
  README.md
  src/Gpio.cpp
  src/WebCfgServer.cpp
  src/enums/NetworkDeviceType.h
  src/networkDevices/W5500Definitions.h
  src/util/NetworkDeviceInstantiator.cpp
  src/util/NetworkUtil.cpp
Labels: enhancement

#614 Duo Push MFA, Coredump saving to flash, remove last_action_authorization and keypad_status from HA, improve HA availability topics
  DUOAUTH.md
  HYBRID.md
  README.md
  lib/DuoAuthLibrary/AUTHORS
  lib/DuoAuthLibrary/CHANGELOG.md
  lib/DuoAuthLibrary/CONTRIBUTING.md
  lib/DuoAuthLibrary/LICENSE
  lib/DuoAuthLibrary/NOTICE
  lib/DuoAuthLibrary/README.md
  lib/DuoAuthLibrary/examples/Common-Functions/Common-Functions.ino
  lib/DuoAuthLibrary/examples/Passcode-Authentication/Passcode-Authentication.ino
  lib/DuoAuthLibrary/examples/Push-ASync-Authentication/Push-ASync-Authentication.ino
  lib/DuoAuthLibrary/examples/Push-Authentication/Push-Authentication.ino
  lib/DuoAuthLibrary/keywords.txt
  lib/DuoAuthLibrary/library.properties
  lib/DuoAuthLibrary/src/DuoAuthLib.cpp
  lib/DuoAuthLibrary/src/DuoAuthLib.h
  lib/MqttLogger/src/MqttLogger.cpp
  lib/MqttLogger/src/MqttLogger.h
  pio_package_post.py
  resources/github_root_ca.pem
  sdkconfig.defaults
  src/Config.h
  src/Gpio.cpp
  src/HomeAssistantDiscovery.cpp
  src/MqttTopics.h
  src/NukiNetwork.cpp
  src/NukiNetworkLock.cpp
  src/NukiNetworkOpener.cpp
  src/PreferencesKeys.h
  src/WebCfgServer.cpp
  src/WebCfgServer.h
  src/main.cpp
  updater/platformio.ini
Labels: bug, documentation, enhancement

#616 Add PIN requirements to README, enlarge IPC stack size
  README.md
  sdkconfig.release.defaults
Labels: documentation

#621 Add info page to main menu, improve CSS, allow BLE transmit power up to 20db, conform to HA guidelines for device config sharing
  README.md
  src/Config.h
  src/HomeAssistantDiscovery.cpp
  src/HomeAssistantDiscovery.h
  src/NukiOpenerWrapper.cpp
  src/NukiWrapper.cpp
  src/WebCfgServer.cpp
  src/WebCfgServerConstants.h
Labels: bug, enhancement
